[package]
name = "oadesktopentry"
edition = "2024"

[dependencies]
openaction = "2.5"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.48", features = ["rt-multi-thread", "macros"] }
base64 = "0.22"
freedesktop-desktop-entry = "0.8"
freedesktop-icons = "0.4.0"
log = "0.4"
simplelog = "0.12"
